[project]
name = "pixi_pytorch"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["win-64"]

[tasks]

[target.win-64.dependencies]
pytorch-cuda = "11.8.*"
torchaudio = "2.0.2.*"
pytorch = "2.0.1.*"
torchvision = "0.15.2.*"

[dependencies]
ipykernel = "6.25.1.*"
