[project]
name = "pixi_pytorch"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["win-64", "osx-arm64", "linux-64"]

[tasks]

# torch release: https://pytorch.org/get-started/previous-versions/
# Updated: 2023-11-29

[target.win-64.dependencies]
 pytorch = "*"
 torchvision = "*"
 torchaudio = "*"
 pytorch-cuda = "*"

[target.osx-arm64.dependencies]
#pytorch-cuda = "*"
#torchaudio = "*"
pytorch = "*"
torchvision = "*"

[target.linux-64.dependencies]
#pytorch = "*"
#torchvision = "*"
#torchaudio = "*"
#pytorch-cuda = "*"
pytorch = "2.2.*"
torchvision = "0.17.*"
torchaudio = "2.2.*"
pytorch-cuda = "12.1"

[dependencies]
python = "~=3.11.*"
jupyter = "1.0.0"
matplotlib = "*"
